# -*- coding: utf-8 -*-
"""CNN Architecture | Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FSJTk9nAap8REJ8LaVb51fRxMcvG0cz

Question 1: What is the role of filters and feature maps in Convolutional Neural
Network (CNN)?

- Role of Filters and Feature Maps in CNN

1. Filters (Kernels)
Filters are small matrices of weights used to scan the input image.
They detect specific features such as edges, corners, textures, shapes, and patterns.
During training, the CNN automatically learns the optimal filter values.
Each filter extracts a different type of feature from the input.

Example:
A filter may detect horizontal edges, while another may detect vertical edges.

2. Feature Maps
A feature map is the output produced after applying a filter to the input image through the convolution operation.
It highlights the locations where the detected feature is present in the image.
Each filter generates one feature map.
Multiple filters produce multiple feature maps, allowing the CNN to learn various features simultaneously.
Working Process
Input image is provided to the CNN.
Filters slide over the image and perform convolution.
The convolution results create feature maps.
Feature maps are passed to subsequent layers for higher-level feature extraction and classification.

Question 2: Explain the concepts of padding and stride in CNNs(Convolutional Neural
Network). How do they affect the output dimensions of feature maps?

- Padding

Padding is the process of adding extra pixels (usually zeros) around the border of an input image before applying the convolution operation.

Purpose:

Prevents loss of information at the image boundaries.
Controls the size of the output feature map.
Allows deeper networks by preserving spatial dimensions.

Types:

Valid Padding: No padding is added.
Same Padding: Padding is added so that the output size remains the same as the input size (for stride = 1).
Stride

Stride is the number of pixels by which the filter moves across the input image during convolution.

Purpose:

Controls how much the filter shifts at each step.
Reduces the spatial dimensions of the output feature map.
Decreases computational cost.

Example:

Stride = 1: Filter moves one pixel at a time.
Stride = 2: Filter moves two pixels at a time, producing a smaller output.
Effect on Output Dimensions

The output size of a feature map is calculated as:

Output Size=
S
(N−F+2P)
	​

+1

Where:

N = Input size
F = Filter size
P = Padding
S = Stride
Impact
Increasing Padding (P): Increases or preserves the output size.
Increasing Stride (S): Decreases the output size.
No Padding and Larger Stride: Produces the smallest feature maps.

Question 3: Define receptive field in the context of CNNs. Why is it important for deep
architectures?

- The receptive field of a neuron in a Convolutional Neural Network (CNN) is the region of the input image that influences the output of that neuron. It represents the portion of the image that the neuron "sees" while extracting features.

Importance in Deep Architectures
Captures More Context: As the network becomes deeper, the receptive field increases, allowing neurons to gather information from larger areas of the input image.
Hierarchical Feature Learning: Early layers detect simple features such as edges and textures, while deeper layers use larger receptive fields to recognize complex patterns and objects.
Improves Object Recognition: A larger receptive field helps the network understand the relationship between distant parts of an image, leading to better classification and detection performance.
Enhances Global Understanding: Deep architectures can capture both local and global image information, which is essential for tasks such as image classification, object detection, and segmentation.

Question 4: Discuss how filter size and stride influence the number of parameters in a
CNN.

- Filter Size

The filter size (kernel size) directly affects the number of trainable parameters in a CNN.

For a convolutional layer:

Number of Parameters=(F
h
	​

×F
w
	​

×C
in
	​

)×C
out
	​

+C
out
	​


Where:

F
h
	​

 = Filter height
F
w
	​

 = Filter width
C
in
	​

 = Number of input channels
C
out
	​

 = Number of filters (output channels)

Effect:

Larger filters (e.g., 5×5, 7×7) have more parameters.
Smaller filters (e.g., 3×3) have fewer parameters and lower computational cost.
Stride

Stride is the number of pixels by which the filter moves across the input.

Effect:

Stride does not affect the number of trainable parameters because it does not change the filter weights.
It affects the size of the output feature map.
Larger strides produce smaller feature maps, reducing computation and memory usage

Question 5: Compare and contrast different CNN-based architectures like LeNet,
AlexNet, and VGG in terms of depth, filter sizes, and performance.

- | Architecture | Depth                                          | Filter Sizes                               | Performance                                                                                                                        |
| ------------ | ---------------------------------------------- | ------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------- |
| **LeNet**    | 5–7 layers                                     | Mainly 5×5 filters                         | Suitable for simple tasks such as handwritten digit recognition; lower accuracy compared to modern CNNs.                           |
| **AlexNet**  | 8 layers (5 convolutional + 3 fully connected) | 11×11, 5×5, and 3×3 filters                | Achieved significantly higher accuracy on large-scale image classification tasks and popularized deep learning in computer vision. |
| **VGG**      | 16 or 19 layers                                | Uniform 3×3 filters throughout the network | Provides higher accuracy and better feature extraction than AlexNet but requires more computation and memory.                      |

Comparison
Depth: LeNet is the shallowest, AlexNet is deeper, and VGG is the deepest among the three.
Filter Sizes: LeNet mainly uses 5×5 filters, AlexNet uses a combination of 11×11, 5×5, and 3×3 filters, while VGG uses only 3×3 filters.
Performance: LeNet performs well on simple datasets, AlexNet greatly improves image classification accuracy, and VGG achieves even better performance due to its deeper architecture and smaller filters.

Question 6: Using keras, build and train a simple CNN model on the MNIST dataset
from scratch. Include code for module creation, compilation, training, and evaluation.
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models

(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

x_train = x_train.reshape((60000, 28, 28, 1)).astype('float32') / 255.0
x_test = x_test.reshape((10000, 28, 28, 1)).astype('float32') / 255.0

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu',
                  input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


model.summary()

history = model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

test_loss, test_accuracy = model.evaluate(x_test, y_test)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

"""Question 7: Load and preprocess the CIFAR-10 dataset using Keras, and create a
CNN model to classify RGB images. Show your preprocessing and architecture.

"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models

(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

print("Training Data Shape:", x_train.shape)
print("Testing Data Shape:", x_test.shape)

model = models.Sequential()

model.add(layers.Conv2D(32, (3,3), activation='relu',
                        input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    x_train,
    y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.2
)

test_loss, test_accuracy = model.evaluate(x_test, y_test)

print("Test Accuracy:", test_accuracy)

"""Question 8: Using PyTorch, write a script to define and train a CNN on the MNIST
dataset. Include model definition, data loaders, training loop, and accuracy evaluation
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_dataset = torchvision.datasets.MNIST(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False
)

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(
            in_channels=1,
            out_channels=32,
            kernel_size=3
        )

        self.pool = nn.MaxPool2d(
            kernel_size=2,
            stride=2
        )

        self.conv2 = nn.Conv2d(
            in_channels=32,
            out_channels=64,
            kernel_size=3
        )

        self.fc1 = nn.Linear(
            64 * 5 * 5,
            128
        )

        self.fc2 = nn.Linear(
            128,
            10
        )

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))

        x = x.view(-1, 64 * 5 * 5)

        x = self.relu(self.fc1(x))
        x = self.fc2(x)

        return x


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CNN().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

num_epochs = 5

for epoch in range(num_epochs):

    running_loss = 0.0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}")


model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs.data, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total

print(f"Test Accuracy: {accuracy:.2f}%")

"""Question 9: Given a custom image dataset stored in a local directory, write code using
Keras ImageDataGenerator to preprocess and train a CNN model.
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.utils import to_categorical

# Load MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Add channel dimension
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# One-hot encode labels
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# CNN Model
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),

    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test, y_test)
)

loss, accuracy = model.evaluate(x_test, y_test)

print("Validation Loss:", loss)
print("Validation Accuracy:", accuracy)

"""Question 10: You are working on a web application for a medical imaging startup. Your
task is to build and deploy a CNN model that classifies chest X-ray images into “Normal”
and “Pneumonia” categories. Describe your end-to-end approach–from data preparation
and model training to deploying the model as a web app using Streamlit.

- To build and deploy a CNN model for classifying chest X-ray images into Normal and Pneumonia, I would follow these steps:

Data Preparation
Collect a labeled chest X-ray dataset.
Split the data into training, validation, and testing sets.
Resize images (e.g., 224×224 pixels) and normalize pixel values.
Apply data augmentation such as rotation, zooming, and flipping to improve generalization.
Model Training
Build a CNN with Convolution, ReLU, Max-Pooling, Flatten, and Dense layers.
Use a Sigmoid output layer for binary classification.
Compile the model using the Adam optimizer and Binary Cross-Entropy loss.
Train the model on the training set and validate it on the validation set.
Use Early Stopping and Dropout to reduce overfitting.
Model Evaluation
Evaluate the trained model on the test dataset.
Measure performance using Accuracy, Precision, Recall, F1-Score, and Confusion Matrix.
Save the trained model (e.g., pneumonia_model.h5).
Streamlit Web Application
Create a Streamlit interface for image upload.
Load the saved CNN model.
Preprocess the uploaded X-ray image.
Predict whether the image belongs to the Normal or Pneumonia class.
Display the prediction and confidence score to the user.
Deployment
Package the Streamlit application and trained model.
Deploy using Streamlit Community Cloud, AWS, Google Cloud, or Azure.
Users can access the web app through a browser, upload chest X-ray images, and receive instant predictions.
"""

