# -*- coding: utf-8 -*-
"""Feature Engineering Assigment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOkvGH8Txx8t9_qUd23TlzM7D9xJeWcn

Q1. What is a parameter?

- A parameter is a numerical value that defines or characterizes a system, model, function, or population. It acts as an input that influences the behavior or output of a process but usually remains fixed during a particular analysis.

Q2. What is correlation?
What does negative correlation mean?

- Correlation is a statistical measure that describes the degree and direction of relationship between two variables. It indicates how changes in one variable are associated with changes in another variable. Correlation values usually range from –1 to +1.
1. A value close to +1 indicates a strong positive relationship.

2. A value close to –1 indicates a strong negative relationship.

3. A value of 0 indicates no linear relationship between the variables.

- Negative Correlation

Negative correlation means that as one variable increases, the other variable decreases, and vice versa. In this case, the correlation coefficient has a negative value (less than 0).

For example, as the price of a product increases, its demand decreases, showing a negative correlation. Similarly, an increase in speed may lead to a decrease in time taken to cover a fixed distance.

Q3. Define Machine Learning. What are the main components in Machine Learning?

- Machine Learning is a branch of Artificial Intelligence (AI) that enables computers to learn from data and improve their performance automatically without being explicitly programmed. In machine learning, systems identify patterns from historical data and use these patterns to make predictions or decisions on new, unseen data.

- Main Components of Machine Learning

1. Data
Data is the foundation of machine learning. It can be structured or unstructured and is used to train and test the model.

2. Model
A model is a mathematical representation that learns patterns from data (e.g., linear regression, decision trees, neural networks).

3. Features
Features are input variables or attributes extracted from raw data that help the model learn effectively.

4. Algorithm
Algorithms are procedures or methods used to train the model by adjusting parameters (e.g., gradient descent, k-means).

5. Loss Function / Evaluation Metric
The loss function measures the error between predicted and actual values, helping determine how well the model performs.

Q4. How does loss value help in determining whether the model is good or not?

- Role of Loss Value in Determining Model Quality

The loss value measures the difference between the predicted output of a model and the actual (true) output. It helps in determining how well a machine learning model is performing.

1. A low loss value indicates that the model’s predictions are very close to the actual values, meaning the model is performing well.

2. A high loss value indicates large prediction errors, showing that the model is not accurate or needs improvement.

During training, the goal of a learning algorithm is to minimize the loss value by adjusting the model parameters (such as weights and bias). By observing the loss value on training and validation data, we can also detect issues like overfitting (very low training loss but high validation loss) or underfitting (high loss on both).

Thus, the loss value acts as a key indicator of model accuracy and reliability, helping decide whether the model is good or needs further tuning.

Q5. What are continuous and categorical variables?

1.  Continuous Variables
Continuous variables are numerical variables that can take any value within a given range. They are measurable and usually represented by real numbers. These variables can have infinite possible values, including decimals and fractions.
Examples: height, weight, temperature, time, distance.

2. Categorical Variables
Categorical variables are variables that represent qualitative data or categories rather than numerical measurements. The values are labels or groups and do not have a mathematical meaning.
Categorical variables are of two main types:

- Nominal: Categories with no natural order (e.g., gender, blood group, color).

- Ordinal: Categories with a meaningful order (e.g., education level, ratings like low–medium–high).

Q6. How do we handle categorical variables in Machine Learning? What are the common t
echniques?

- Categorical variables cannot be directly used in most machine learning algorithms, so they must be converted into numerical form. This process is called categorical encoding.

- Common Techniques to Handle Categorical Variables

1. Label Encoding
Each category is assigned a unique numeric value.
Example: Red = 0, Blue = 1, Green = 2
Suitable for ordinal data where order matters.

2. One-Hot Encoding
Creates separate binary columns for each category.
Example: Color → Red(1/0), Blue(1/0), Green(1/0)
Commonly used for nominal data.

3. Ordinal Encoding
Categories are encoded based on their order or rank.
Example: Low = 1, Medium = 2, High = 3.

4. Binary Encoding
Categories are converted into binary numbers to reduce dimensionality.
Useful when there are many categories.

5. Target Encoding (Mean Encoding)
Categories are replaced with the mean of the target variable for that category.
Often used in advanced models but requires care to avoid overfitting.

Q7. What do you mean by training and testing a dataset?

- Training Dataset
The training dataset is the portion of data used to train the machine learning model. The model learns patterns, relationships, and parameters (such as weights and bias) from this data. It helps the algorithm understand how input features are related to the output.

- Testing Dataset
The testing dataset is used to evaluate the performance of the trained model on unseen data. It checks how well the model can generalize to new data and helps measure accuracy, error, or other evaluation metrics.

Q8. What is sklearn preprocessing?

- sklearn.preprocessing is a module of the Scikit-learn (sklearn) library in Python that provides tools for preprocessing and transforming data before applying machine learning algorithms.

- It is used to convert raw data into a suitable numerical format, scale features, and encode categorical variables so that machine learning models can perform efficiently and accurately.

- Main uses of sklearn.preprocessing:

1. Feature scaling (StandardScaler, MinMaxScaler)

2. Normalization of data (Normalizer)

3. Encoding categorical data (LabelEncoder, OneHotEncoder)

4. Binarization of values

5. Handling data consistency

Q9. What is a Test set?

- A test set is a portion of the dataset that is kept separate from the training process and is used to evaluate the performance of a trained machine learning model. It contains data that the model has never seen during training, making it essential for measuring how well the model generalizes to new, real-world data.

The main purpose of the test set is to provide an unbiased evaluation of the final model. By comparing the model’s predictions on the test set with the actual output values, we can calculate performance metrics such as accuracy, precision, recall, error rate, or loss.

Using a test set helps in detecting problems like overfitting, where a model performs well on training data but poorly on unseen data. Typically, datasets are split into training and testing sets in ratios such as 70:30 or 80:20.

Thus, the test set plays a crucial role in validating the reliability, accuracy, and effectiveness of a machine learning model.

Q10. How do we split data for model fitting (training and testing) in Python?
How do you approach a Machine Learning problem?

- In Python, data is commonly split into training and testing sets using the Scikit-learn library. The most widely used method is train_test_split() from sklearn.model_selection.

The dataset is divided so that the training set is used to train the model, while the testing set is used to evaluate its performance.

A common split ratio is 70:30 or 80:20.

Random splitting ensures unbiased data distribution.

EXAMPLE - from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

2. How do you approach a Machine Learning problem?

- A machine learning problem is approached in a systematic and structured manner as follows:

1. Problem Understanding
Clearly define the problem and identify whether it is a classification, regression, or clustering task.

2. Data Collection
Gather relevant and sufficient data from reliable sources.

3. Data Preprocessing
Handle missing values, encode categorical variables, and scale numerical features.

4. Feature Selection / Engineering
Select important features or create new ones to improve model performance.

5. Model Selection and Training
Choose an appropriate algorithm and train it using the training dataset.

6. Model Evaluation
Evaluate performance using metrics like accuracy, precision, recall, or loss on the test set.

7. Model Improvement
Tune hyperparameters and improve the model if required.

Q11.Why do we have to perform EDA before fitting a model to the data?

- Exploratory Data Analysis (EDA) is performed before fitting a model to understand the data thoroughly and ensure its quality. It helps in identifying important patterns, trends, and potential issues in the dataset.

Firstly, EDA helps in detecting missing values, outliers, and inconsistencies in the data. Handling these issues early prevents misleading results and improves model accuracy.

Secondly, EDA allows us to understand the distribution of variables and the relationship between features and the target variable. This helps in selecting suitable features and choosing an appropriate machine learning algorithm.

Thirdly, EDA helps in identifying correlation and multicollinearity among variables, which can negatively affect model performance.

Finally, by visualizing and summarizing the data, EDA supports better feature engineering and preprocessing decisions, leading to improved model performance.

Thus, EDA is essential before model fitting to ensure clean data, correct assumptions, and reliable model results.

Q12. What is correlation?

- Correlation is a statistical measure that describes the strength and direction of the relationship between two variables. It shows how one variable changes in relation to another.

The value of correlation usually lies between –1 and +1:

1. +1 indicates a perfect positive correlation (both variables increase or decrease together).

2. –1 indicates a perfect negative correlation (one variable increases while the other decreases).

3. 0 indicates no linear relationship between the variables.

Q13. What does negative correlation mean?

- Negative correlation refers to a relationship between two variables in which an increase in one variable leads to a decrease in the other, and vice versa. In this case, the correlation coefficient has a negative value (less than 0).

For example, as the speed of a vehicle increases, the time taken to cover a fixed distance decreases. Similarly, an increase in the price of a product often results in a decrease in its demand.

Q14. How can you find correlation between variables in Python?
"""

import pandas as pd

# Sample DataFrame
data = {
    'Study_Hours': [2, 4, 6, 8, 10],
    'Marks': [40, 50, 65, 80, 90]
}

df = pd.DataFrame(data)

# Find correlation
correlation = df.corr()
print(correlation)

import numpy as np

x = [2, 4, 6, 8, 10]
y = [40, 50, 65, 80, 90]

corr = np.corrcoef(x, y)
print(corr)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(df.corr(), annot=True)
plt.show()

"""Q15. What is causation? Explain difference between correlation and causation with an example.

- Causation refers to a relationship where a change in one variable directly produces a change in another variable. It represents a cause-and-effect relationship, meaning one event (cause) is responsible for the occurrence of another event (effect).

Difference between Correlation and Causation

| Basis     | Correlation                             | Causation                                      |
| --------- | --------------------------------------- | ---------------------------------------------- |
| Meaning   | Shows association between two variables | Shows cause-and-effect relationship            |
| Effect    | Variables change together               | One variable directly causes change in another |
| Direction | Can be positive or negative             | Always directional (cause → effect)            |
| Proof     | Does not confirm cause                  | Requires logical or experimental evidence      |

Q16. What is an Optimizer? What are different types of optimizers? Explain each with an example ?

- An optimizer is a technique or algorithm used in machine learning and deep learning to minimize the loss function by adjusting the model’s parameters (such as weights and bias). It controls how the model learns from data and directly affects training speed, convergence, and accuracy.

- Types of Optimizers

1. Gradient Descent (GD)
Gradient Descent updates parameters using the entire training dataset in each iteration to reduce loss.
Example: Used in simple linear regression to find the best-fit line.

2. Stochastic Gradient Descent (SGD)
SGD updates parameters using one data point at a time, making learning faster but noisier.
Example: Commonly used in large datasets and neural networks.

3. Mini-Batch Gradient Descent
This method updates parameters using a small batch of data instead of the full dataset.
Example: Widely used in deep learning models like CNNs.

4. Momentum
Momentum optimizer accelerates gradient descent by considering past gradients, helping avoid local minima.
Example: Used in deep neural networks to improve convergence speed.

5. Adam (Adaptive Moment Estimation)
Adam combines Momentum and RMSProp, adapting the learning rate for each parameter.

Q17. What is sklearn.linear_model ?

-  sklearn.linear_model is a module in the Scikit-learn library that provides classes and functions to implement linear models for regression and classification tasks in machine learning. These models assume a linear relationship between input features and the target variable.

- This module is widely used because it is simple, efficient, and easy to interpret, making it suitable for both beginners and real-world applications.

- Main models provided by sklearn.linear_model include:

1. LinearRegression – used for predicting continuous values

2. LogisticRegression – used for classification problems

3. Ridge Regression – linear regression with L2 regularization

4. Lasso Regression – linear regression with L1 regularization

5. ElasticNet – combination of Ridge and Lasso

sklearn.linear_model also includes optimization techniques like stochastic gradient descent for training large-scale linear models.

Thus, sklearn.linear_model is an important module for building simple, fast, and interpretable machine learning models based on linear relationships

Q18. What does model.fit() do? What arguments must be given?

- model.fit() is a method used to train a machine learning model. It allows the model to learn patterns and relationships from the training data by adjusting its internal parameters (such as weights and bias) to minimize the loss or error.

In simple terms, model.fit() tells the algorithm to learn from the provided data.

The required arguments are:

1. X (Features / Input data)

- A 2D array or DataFrame containing the independent variables.

- Example: X_train

2. y (Target / Output data)

- A 1D array or Series containing the dependent variable.

- Example: y_train

model.fit(X_train, y_train)

Q19. What does model.predict() do? What arguments must be given?

- model.predict() is a method used to generate predictions from a trained machine learning model. After the model has been trained using model.fit(), this method uses the learned parameters to predict output values for new or unseen input data.

In simple terms, model.predict() applies the trained model to input data and returns the predicted results.

- The required argument is:

1. X (Input / Feature data)

- A 2D array, list, or DataFrame containing the independent variables.

- This data can be test data or new data.

- Example: X_test

Syntax: predictions = model.predict(X_test)

Q20. What are continuous and categorical variables?

1.  Continuous Variables
Continuous variables are numerical variables that can take any value within a given range. They are measurable and usually represented by real numbers. These variables can have infinite possible values, including decimals and fractions.
Examples: height, weight, temperature, time, distance.

2. Categorical Variables
Categorical variables are variables that represent qualitative data or categories rather than numerical measurements. The values are labels or groups and do not have a mathematical meaning.
Categorical variables are of two main types:

- Nominal: Categories with no natural order (e.g., gender, blood group, color).

- Ordinal: Categories with a meaningful order (e.g., education level, ratings like low–medium–high).

Q21. What is feature scaling? How does it help in Machine Learning?

- Feature scaling is a data preprocessing technique used to bring all numerical features to a common scale without changing their relative relationships. It ensures that features with different units or ranges are treated equally by machine learning algorithms.

Common feature scaling methods include Normalization (Min–Max scaling) and Standardization (Z-score scaling).

-  How Feature Scaling Helps in Machine Learning

1. Improves Model Performance
Algorithms like linear regression, logistic regression, SVM, and KNN perform better when features are on a similar scale.

2. Faster Convergence
Feature scaling helps optimization algorithms such as gradient descent converge faster by preventing large-value features from dominating updates.

3. Prevents Bias Due to Magnitude
Without scaling, features with larger numeric ranges can dominate the learning process, leading to biased models.

4. Better Distance Calculation
Distance-based algorithms (KNN, K-means) rely on distances; scaling ensures accurate distance measurement.

5. Numerical Stability
Scaling improves computational stability and reduces the risk of numerical errors.

Q22. How do we perform scaling in Python?

- Feature scaling in Python is commonly done using the Scikit-learn (sklearn) preprocessing module. It helps bring numerical features to a similar scale so that machine learning algorithms perform efficiently.

- Standardization scales data to have mean = 0 and standard deviation = 1.
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

- Normalization scales data to a fixed range, usually 0 to 1.

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

- RobustScaler uses median and interquartile range, making it robust to outliers.
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

Q23.What is sklearn preprocessing?

- sklearn.preprocessing is a module of the Scikit-learn (sklearn) library in Python that provides tools for preprocessing and transforming data before applying machine learning algorithms.

- It is used to convert raw data into a suitable numerical format, scale features, and encode categorical variables so that machine learning models can perform efficiently and accurately.

- Main uses of sklearn.preprocessing:

1. Feature scaling (StandardScaler, MinMaxScaler)

2. Normalization of data (Normalizer)

3. Encoding categorical data (LabelEncoder, OneHotEncoder)

4. Binarization of values

5. Handling data consistency

Q24. How do we split data for model fitting (training and testing) in Python?


- In Python, data is commonly split into training and testing sets using the Scikit-learn library. The most widely used method is train_test_split() from sklearn.model_selection.

The dataset is divided so that the training set is used to train the model, while the testing set is used to evaluate its performance.

A common split ratio is 70:30 or 80:20.

Random splitting ensures unbiased data distribution.

EXAMPLE - from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Q25. Explain data encoding?

Data encoding is the process of converting categorical (non-numerical) data into numerical form so that it can be used by machine learning algorithms. Most ML models work only with numbers, so encoding is an essential data preprocessing step.

- Why Data Encoding is Needed

- Machine learning algorithms perform mathematical operations, which require numeric input.

- Categorical values like “Red”, “Male”, or “Yes” must be converted into numbers.

- Proper encoding helps improve model accuracy and efficiency.

- Common Data Encoding Techniques

1. Label Encoding
Each category is assigned a unique integer.
Example:
Male = 0, Female = 1
Used mainly for ordinal data.

4. One-Hot Encoding
Creates separate binary columns for each category.
Example:
Color → Red(1,0,0), Blue(0,1,0), Green(0,0,1)
Best for nominal data.

3. Ordinal Encoding
Encodes categories based on their order.
Example: Low = 1, Medium = 2, High = 3.

4. Binary Encoding
Converts categories into binary numbers to reduce dimensionality.

5. Target Encoding
Replaces categories with the mean of the target variable for that category.
"""

