# -*- coding: utf-8 -*-
"""Statistics Advanced - 1 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MV3DTtj2s-16xBDd0CctSNgAm1LN1ocA

Question 1: What is a random variable in probability theory?

- A random variable is a variable that represents the numerical outcome of a random experiment. It is a function that assigns a real number to each element of the sample space of a probabilistic experiment. Random variables allow us to analyze random phenomena using mathematical and statistical methods.

Random variables are mainly classified into two types. A discrete random variable takes a finite or countable set of values, such as the number of students present in a class or the number of heads in coin tosses. A continuous random variable can take any value within a specified range, such as height, weight, or time.

Random variables are important because they help in defining probability distributions and are used to calculate statistical measures like mean, variance, and standard deviation. They form the basis for probability models and decision-making under uncertainty.

For example, when a die is rolled, the random variable
𝑋
X representing the number on the top face can take values
1
,
2
,
3
,
4
,
5
,
1,2,3,4,5, or
6
6.

Question 2: What are the types of random variables?
- Random variables are classified based on the nature of values they can take. There are two main types of random variables:

1. Discrete Random Variable
A discrete random variable takes a finite or countable number of distinct values. Each value has a specific probability associated with it.
Examples:

- Number of heads in a series of coin tosses

- Number of students present in a class

- Outcome of rolling a die (1 to 6)

2. Continuous Random Variable
A continuous random variable can take any value within a given interval or range. The number of possible values is uncountably infinite, and probabilities are described using a probability density function (PDF).
Examples:

- Height or weight of a person

- Time taken to complete a task

- Temperature of a room

Question 3: Explain the difference between discrete and continuous distributions.

- A discrete distribution is associated with a discrete random variable, which takes a finite or countable number of distinct values. In a discrete distribution, the probability of each possible value is defined using a probability mass function (PMF), and the sum of all probabilities is equal to 1.
Examples of discrete distributions include the Binomial distribution, Poisson distribution, and outcomes of rolling a die.

- A continuous distribution is associated with a continuous random variable, which can take any value within a given range or interval. Probabilities are described using a probability density function (PDF). In this case, the probability of the random variable taking any exact value is zero, and probabilities are found over intervals. The total area under the PDF curve is equal to 1.
Examples of continuous distributions include the Normal distribution, Exponential distribution, and Uniform distribution.

Question 4: What is a binomial distribution, and how is it used in probability?

- A binomial distribution is a discrete probability distribution that describes the number of successes in a fixed number of independent trials of a random experiment. Each trial has only two possible outcomes, commonly called success and failure, and the probability of success remains constant in every trial.

A binomial distribution is characterized by two parameters:

- n: the number of trials
- p: the probability of success in each trial

-->> The probability of obtaining exactly x successes in n trials is given by the formula:

 p(X = x) = (n/x)px(1-p)n-x

- Conditions for Binomial Distribution:

1. Fixed number of trials

2. Each trial is independent

3. Only two possible outcomes per trial

4. Constant probability of success

Question 5: What is the standard normal distribution, and why is it important ?

- The standard normal distribution is a special type of normal distribution with a mean of 0 and a standard deviation of 1. It is a continuous, symmetric, bell-shaped probability distribution centered at zero. The random variable that follows a standard normal distribution is usually denoted by Z.

Any normal random variable X with mean μ and standard deviation σ can be converted into a standard normal variable using the z-score formula:

   Z = X-μ/σ

- Importance of Standard Normal Distribution:

1. It allows comparison of values from different normal distributions using z-scores.

2. Probabilities and percentiles can be easily found using standard normal tables (Z-tables).

3. It simplifies statistical analysis and hypothesis testing.

4. It is widely used in confidence intervals, quality control, and inferential statistics.

Question 6: What is the Central Limit Theorem (CLT), and why is it critical in statistics?

-  The Central Limit Theorem (CLT) states that when a large number of independent and identically distributed random samples are drawn from any population with a finite mean and variance, the sampling distribution of the sample mean tends to follow a normal distribution, irrespective of the original population’s distribution.

- According to CLT, if the population mean is μ and population standard deviation is σ, then for a sufficiently large sample size n, the sample mean has a mean μ and standard deviation

                     σ/n

- Importance of CLT:

It allows the use of normal distribution in statistical analysis.

It forms the foundation of hypothesis testing and confidence intervals.

It simplifies complex real-life data analysis.

It is widely used in surveys, quality control, and inferential statistics.

Question 7: What is the significance of confidence intervals in statistical analysis ?

-  A confidence interval (CI) is a range of values, calculated from sample data, within which the true population parameter (such as mean or proportion) is expected to lie with a specified level of confidence (for example, 95% or 99%).

- Significance of Confidence Intervals:

1. They provide an estimate of uncertainty associated with a sample statistic.

2. Confidence intervals give more information than point estimates by showing a range of plausible values.

3. They help in statistical inference and decision-making.

4. The width of a confidence interval indicates the precision of the estimate (narrower intervals imply higher precision).

5. They are widely used in hypothesis testing, research studies, and real-world data analysis.

Question 8: What is the concept of expected value in a probability distribution?

- The expected value of a probability distribution is the theoretical mean or average value of a random variable. It represents the value that is expected to occur in the long run when a random experiment is repeated many times.

- For a discrete random variable, the expected value is calculated by multiplying each possible value of the variable by its probability and then summing the results:

              E(X)=∑xP(X=x)
- For a continuous random variable, the expected value is obtained using the probability density function:

              E(X)=∫−∞∞​xf(x)dx

- Significance of Expected Value:

1. It provides a measure of central tendency of the distribution.

2. It helps in decision-making under uncertainty.

3. It is used to compute variance and standard deviation.

4. It is widely applied in statistics, economics, and probability theory.

Question 9: Write a Python program to generate 1000 random numbers from a normal
distribution with mean = 50 and standard deviation = 5. Compute its mean and standard
deviation using NumPy, and draw a histogram to visualize the distribution
"""

import numpy as np
import matplotlib.pyplot as plt
data = np.random.normal(loc=50, scale=5, size=1000)
mean = np.mean(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Standard Deviation:", std_dev)
plt.hist(data, bins=30)
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.title("Histogram of Normal Distribution (Mean=50, Std=5)")
plt.show()

"""Question 10: You are working as a data analyst for a retail company. The company has
collected daily sales data for 2 years and wants you to identify the overall sales trend.

-  As a data analyst, to identify the overall sales trend from daily sales data collected over 2 years, the following approach can be used:

1. Data Preparation:
First, clean the dataset by handling missing values, removing duplicates, and ensuring the date column is in proper date format. Then, sort the data chronologically.

2. Aggregation of Data:
Daily sales data can be aggregated into weekly or monthly sales to reduce noise and make long-term trends more visible.

3. Visualization:
Plot a time series line graph of sales versus time. This helps visually identify whether sales are increasing, decreasing, or remaining stable over the 2-year period.

4. Trend Analysis Techniques:
Apply techniques such as moving averages or trend lines (linear regression) to smooth short-term fluctuations and highlight the overall trend.

5. Interpretation:
Analyze the trend to conclude whether sales show growth, decline, or seasonality. These insights help management in forecasting, inventory planning, and strategic decision-making.
"""

