# -*- coding: utf-8 -*-
"""Statistics Advanced - 2| Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eb-uNXFRlfXLzMKnCK2uPm-w2u_hsLfR

Question 1: What is hypothesis testing in statistics?

- Hypothesis testing is a statistical procedure used to make decisions about a population based on sample data. It helps determine whether there is enough evidence to support or reject a given assumption.

It involves two hypotheses: the null hypothesis (H₀), which states that there is no effect or no difference, and the alternative hypothesis (H₁), which states that an effect or difference exists. A suitable test statistic (such as z-test, t-test, or chi-square test) is calculated from the sample data.

The decision is made using a significance level (α), usually 0.05. If the calculated p-value is less than α, the null hypothesis is rejected; otherwise, it is not rejected.

Thus, hypothesis testing provides a systematic and scientific method for drawing conclusions and making inferences in statistics.

Question 2: What is the null hypothesis, and how does it differ from the alternative hypothesis?
- The null hypothesis (H₀) is a statistical statement that assumes there is no effect, no difference, or no relationship between variables in a population. It represents the default or initial assumption and is tested using sample data.

The alternative hypothesis (H₁ or Hₐ) is the statement that contradicts the null hypothesis. It suggests that there is an effect, a difference, or a relationship in the population.

The main difference between them is that the null hypothesis is tested for possible rejection, while the alternative hypothesis is accepted only when sufficient evidence is found against H₀. In hypothesis testing, statistical tests determine whether the sample data provide enough evidence to reject the null hypothesis in favor of the alternative hypothesis.

- Example:

1. H₀: The average marks of students is 70.

2. H₁: The average marks of students is not 70.

Question 3: Explain the significance level in hypothesis testing and its role in deciding the outcome of a test ?

- The significance level, denoted by α (alpha), is the probability of rejecting the null hypothesis when it is actually true. It represents the maximum allowable risk of making a Type I error.

Commonly used significance levels are 0.05, 0.01, and 0.10. A significance level of 0.05 means there is a 5% chance of incorrectly rejecting a true null hypothesis.

The significance level plays a crucial role in decision-making. After computing the p-value from the test statistic, it is compared with α.

If p-value ≤ α, the null hypothesis is rejected.

If p-value > α, the null hypothesis is not rejected.

Thus, the significance level helps determine whether the observed results are statistically significant and provides a clear criterion for accepting or rejecting the null hypothesis.

Question 4: What are Type I and Type II errors? Give examples of each ?

- In hypothesis testing, Type I and Type II errors are errors that occur while making a decision about the null hypothesis.

A Type I error occurs when the null hypothesis (H₀) is rejected even though it is true. It is also known as a false positive. The probability of committing a Type I error is equal to the significance level (α).
Example: A medical test indicates that a person has a disease when, in reality, the person is healthy.

A Type II error occurs when the null hypothesis is not rejected even though it is false. It is also called a false negative. The probability of a Type II error is denoted by β.
Example: A medical test fails to detect a disease in a person who actually has the disease.

Thus, Type I and Type II errors explain the risks involved in hypothesis testing decisions.

Question 5: What is the difference between a Z-test and a T-test? Explain when to use each ?

- A Z-test and a T-test are statistical tests used to determine whether there is a significant difference between sample and population means, but they are used under different conditions.

A Z-test is used when the sample size is large (n ≥ 30) and the population standard deviation is known. It is based on the normal distribution and is commonly applied in large-sample studies.

A T-test is used when the sample size is small (n < 30) and the population standard deviation is unknown. It is based on the Student’s t-distribution, which accounts for extra variability in small samples.

Summary of Differences:

Z-test → large sample size, known population standard deviation

T-test → small sample size, unknown population standard deviation

Thus, the choice between a Z-test and a T-test depends on sample size and whether the population standard deviation is known.

Question 6: Write a Python program to generate a binomial distribution with n=10 and p=0.5, then plot its histogram ?
"""

import numpy as np
import matplotlib.pyplot as plt


n = 10
p = 0.5
size = 1000
data = np.random.binomial(n, p, size)


plt.hist(data, bins=range(n+2), edgecolor='black')
plt.xlabel("Number of Successes")
plt.ylabel("Frequency")
plt.show()

"""Question 7: Implement hypothesis testing using Z-statistics for a sample dataset in
Python. Show the Python code and interpret the results.
sample_data = [49.1, 50.2, 51.0, 48.7, 50.5, 49.8, 50.3, 50.7, 50.2, 49.6,
50.1, 49.9, 50.8, 50.4, 48.9, 50.6, 50.0, 49.7, 50.2, 49.5,
50.1, 50.3, 50.4, 50.5, 50.0, 50.7, 49.3, 49.8, 50.2, 50.9,
50.3, 50.4, 50.0, 49.7, 50.5, 49.9]

"""

import numpy as np
from scipy.stats import norm

sample_data = [49.1, 50.2, 51.0, 48.7, 50.5, 49.8, 50.3, 50.7, 50.2, 49.6,
               50.1, 49.9, 50.8, 50.4, 48.9, 50.6, 50.0, 49.7, 50.2, 49.5,
               50.1, 50.3, 50.4, 50.5, 50.0, 50.7, 49.3, 49.8, 50.2, 50.9,
               50.3, 50.4, 50.0, 49.7, 50.5, 49.9]

mu = 50

sample_mean = np.mean(sample_data)
sample_std = np.std(sample_data, ddof=1)
n = len(sample_data)


z = (sample_mean - mu) / (sample_std / np.sqrt(n))
p_value = 2 * (1 - norm.cdf(abs(z)))

print("Sample Mean:", sample_mean)
print("Z-statistic:", z)
print("P-value:", p_value)

"""Question 8: Write a Python script to simulate data from a normal distribution and
calculate the 95% confidence interval for its mean. Plot the data using Matplotlib.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm


mean = 50
std_dev = 5
n = 1000
confidence_level = 0.95


data = np.random.normal(mean, std_dev, n)


sample_mean = np.mean(data)
sample_std = np.std(data, ddof=1)


z_critical = norm.ppf(1 - (1 - confidence_level) / 2)
margin_of_error = z_critical * (sample_std / np.sqrt(n))

lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error


print("Sample Mean:", sample_mean)
print("95% Confidence Interval:", (lower_bound, upper_bound))


plt.hist(data, bins=30, edgecolor='black')
plt.axvline(sample_mean, linestyle='--', label='Sample Mean')
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.title("Normal Distribution Histogram")
plt.legend()
plt.show()

"""Question 9: Write a Python function to calculate the Z-scores from a dataset and
visualize the standardized data using a histogram. Explain what the Z-scores represent
in terms of standard deviations from the mean.

"""

import numpy as np
import matplotlib.pyplot as plt

def calculate_z_scores(data):
    mean = np.mean(data)
    std = np.std(data, ddof=1)
    z_scores = (data - mean) / std
    return z_scores


data = np.array([45, 48, 50, 52, 49, 51, 53, 47, 46, 54])


z_scores = calculate_z_scores(data)


print("Z-scores:", z_scores)

plt.hist(z_scores, bins=10, edgecolor='black')
plt.xlabel("Z-score")
plt.ylabel("Frequency")
plt.title("Histogram of Standardized Data (Z-scores)")
plt.show()

