# -*- coding: utf-8 -*-
"""Statistics Basics| Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqD-XJWoKwKxlpZKsDnS0BdYqUTcyfmK

Question 1: What is the difference between descriptive statistics and inferential
statistics? Explain with examples.

- Descriptive statistics deals with collecting, organizing, summarizing, and presenting data in a meaningful way. It describes the main features of a dataset using measures such as mean, median, mode, standard deviation, and graphical representations like tables and charts.
Example: Calculating the average marks of students in a class or showing sales data using a bar graph.

- Inferential statistics deals with drawing conclusions, making predictions, or generalizations about a population based on a sample of data. It uses probability theory and methods such as hypothesis testing, confidence intervals, correlation, and regression.
Example: Using the marks of some students to estimate the average marks of all students in a college or predicting future sales from past data.

Thus, descriptive statistics summarizes data, whereas inferential statistics helps in decision-making about a population.

Question 2: What is sampling in statistics? Explain the differences between random
and stratified sampling.

- Sampling in statistics is the process of selecting a subset (sample) from a large group called a population in order to study its characteristics. Sampling is used because studying the entire population is often time-consuming, costly, and impractical. The results obtained from the sample are used to make conclusions about the population.

1. Random Sampling

- In random sampling, every member of the population has an equal and independent chance of being selected.

- Characteristics:

- Selection is purely by chance

- Simple and unbiased

- Suitable for homogeneous populations

- Example:
Selecting 50 students randomly from a college using a lottery method.

2. Stratified Sampling

- In stratified sampling, the population is first divided into subgroups (strata) based on a specific characteristic, and then samples are randomly selected from each stratum.

- Characteristics:

- Ensures representation of all subgroups

- More accurate than random sampling

- Suitable for heterogeneous populations

- Example:
Dividing students into groups based on year (1st, 2nd, 3rd year) and selecting students from each group.

Question 3: Define mean, median, and mode. Explain why these measures of central
tendency are important.

-  Mean is the arithmetic average of a set of observations. It is calculated by dividing the sum of all values by the total number of values.
Mean = (Sum of observations) / (Number of observations)

- Median is the middle value of a dataset when the observations are arranged in ascending or descending order. If the number of observations is even, the median is the average of the two middle values.

- Mode is the value that occurs most frequently in a dataset. A dataset may have one mode, more than one mode, or no mode.

- Importance of Measures of Central Tendency

-->>  Measures of central tendency are important because they:

1. Provide a single representative value for a large dataset

2. Help in comparing different datasets easily

3. Simplify data analysis and interpretation

4. Are widely used in statistics, economics, business, and research

5. Help in decision-making by summarizing data effectively

Question 4: Explain skewness and kurtosis. What does a positive skew imply about the
data?

- Skewness is a statistical measure that describes the degree of asymmetry of a data distribution around its mean. It shows whether the data is spread more to the left or to the right of the central value.

1. Positive skewness (right-skewed): The tail of the distribution is longer on the right side.

2. Negative skewness (left-skewed): The tail is longer on the left side.

3. Zero skewness: The distribution is symmetrical.

- Kurtosis is a measure that describes the peakedness or flatness of a distribution compared to a normal distribution.

1.  Leptokurtic: Highly peaked with heavy tails

2. Mesokurtic: Normal peak

3. Platykurtic: Flat peak with light tails

- Meaning of Positive Skew

- A positive skew implies that:

1. Most of the data values are concentrated on the lower side

2. A few high extreme values stretch the distribution to the right

3. Generally, Mean > Median > Mode

Example:
Income distribution where most people earn low to medium income, but a few people earn very high income.

Question 5: Implement a Python program to compute the mean, median, and mode of
a given list of numbers.
"""

from statistics import mean, median, mode

data = [2, 4, 6, 8, 4, 10, 4]


mean_value = mean(data)
median_value = median(data)
mode_value = mode(data)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)

"""Question 6: Compute the covariance and correlation coefficient between the following two datasets provided as lists in Python:"""

import numpy as np

X = [10, 20, 30, 40, 50]
Y = [15, 25, 35, 45, 60]

x = np.array(X)
y = np.array(Y)

covariance = np.cov(x, y)[0][1]

correlation = np.corrcoef(x, y)[0][1]

print("Covariance:", covariance)
print("Correlation Coefficient:", correlation)

"""Question 7: Write a Python script to draw a boxplot for the following numeric list and identify its outliers. Explain the result:

"""

import matplotlib.pyplot as plt

data = [10, 12, 14, 15, 18, 19, 20, 22, 25, 100]


plt.boxplot(data)
plt.title("Boxplot of Given Data")
plt.ylabel("Values")
plt.show()

"""Question 8: You are working as a data analyst in an e-commerce company. The
marketing team wants to know if there is a relationship between advertising spend and daily sales ?

- As a data analyst, to determine whether there is a relationship between advertising spend and daily sales, I would use statistical analysis techniques such as correlation and regression analysis.

First, I would collect historical data on daily advertising expenditure and the corresponding daily sales figures. After cleaning and organizing the data, I would compute the correlation coefficient to measure the strength and direction of the relationship. A positive correlation would indicate that higher advertising spend is associated with higher sales.

Next, I would apply regression analysis, where advertising spend is treated as the independent variable and daily sales as the dependent variable. This helps in understanding how much sales change with a unit increase in advertising spend and in predicting future sales.

Additionally, I would visualize the data using a scatter plot to observe any visible trend or pattern between the two variables.

Question 9: Your team has collected customer satisfaction survey data on a scale of 1-10 and wants to understand its distribution before launching a new product.

- To understand the distribution of customer satisfaction survey data (scale 1–10) before launching a new product, the following steps can be taken:

First, I would use descriptive statistics such as mean, median, mode, range, and standard deviation to summarize the overall satisfaction level and variability in responses.

Second, I would visualize the data using graphs like a histogram or boxplot. A histogram helps in identifying the shape of the distribution (normal, skewed, or uniform), while a boxplot helps detect outliers and spread of the data.

Third, I would analyze skewness and kurtosis to understand whether customer responses are biased toward higher or lower ratings and whether the data is peaked or flat.

Finally, I would segment the data (if needed) based on factors like customer type or region to gain deeper insights.
"""

